// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVenda.DAL;

namespace SistemaVenda.Repositorio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210102033305_initial-create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("Codigo");

                    b.ToTable("CATEGORIA");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF_CNPJ")
                        .IsRequired()
                        .HasColumnName("CPF_CNPJ")
                        .HasColumnType("VARCHAR(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnName("CELULAR")
                        .HasColumnType("VARCHAR(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("Codigo");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCategoria")
                        .HasColumnName("CODIGO_CATEGORIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<double>("Quantidade")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("Valor")
                        .HasColumnName("VALOR")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCategoria");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("NOME")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA")
                        .HasColumnType("VARCHAR(20)")
                        .HasMaxLength(20);

                    b.HasKey("Codigo");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Venda", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CODIGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCliente")
                        .HasColumnName("CODIGO_CLIENTE");

                    b.Property<DateTime>("Data")
                        .HasColumnName("DATA")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Total")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoCliente");

                    b.ToTable("VENDA");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.VendaProdutos", b =>
                {
                    b.Property<int>("CodigoProduto")
                        .HasColumnName("CODIGO_PRODUTO");

                    b.Property<int>("CodigoVenda")
                        .HasColumnName("CODIGO_VENDA");

                    b.Property<double>("Quantidade")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("VALOR_TOTAL")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnName("VALOR_UNITARIO")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("CodigoProduto", "CodigoVenda");

                    b.HasIndex("CodigoVenda");

                    b.ToTable("VENDA_PRODUTOS");
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Produto", b =>
                {
                    b.HasOne("SistemaVenda.Dominio.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodigoCategoria")
                        .HasConstraintName("FK_PRODUTO_CATEGORIA_CODIGO_CATEGORIA")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.Venda", b =>
                {
                    b.HasOne("SistemaVenda.Dominio.Entidades.Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("CodigoCliente")
                        .HasConstraintName("FK_VENDA_CLIENTE_CODIGO_CLIENTE")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaVenda.Dominio.Entidades.VendaProdutos", b =>
                {
                    b.HasOne("SistemaVenda.Dominio.Entidades.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("CodigoProduto")
                        .HasConstraintName("FK_VENDA_PRODUTO_PRODUTO_CODIGO_PRODUTO")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaVenda.Dominio.Entidades.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("CodigoVenda")
                        .HasConstraintName("FK_VENDA_PRODUTO_VENDA_CODIGO_VENDA")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
